### PR TITLE
logo and background

### PR DESCRIPTION
**Pull request by Suparnapaul393**
Added a logo and changed the image slider

### CODE REVIEW

**Comment by pbiswas101** [comment]
Send a link to the live version of your request! Or a screenshot!

**Comment by shashank-sharma** [comment]
14,214 addition ... It's too much, I guess the indentation have been changed. Also If possible please remove .Ds_Store binary file. Just add it in gitignore.

**Comment by Suparnapaul393** [comment]
Ok i will do that just guide me on how to be done


On Sat, Apr 14, 2018 at 1:49 PM, Priyabrata Biswas <notifications@github.com

**Comment by Suparnapaul393** [comment]
https://github.com/Suparnapaul393/task-master link to my repo

**Comment by pbiswas101** [comment]
Go to your repo's settings, below you'll find GitHub pages & then select **Master Branch** instead of **None** Then share the link with _github.io_

**Comment by Suparnapaul393** [comment]
https://suparnapaul393.github.io/task-master/

On Sat, Apr 14, 2018 at 2:03 PM, Priyabrata Biswas <notifications@github.com

**Comment by Suparnapaul393** [comment]
I will recheck it and send it back by evening... I haven't made much
changes only added a logo and changed the sliding background images.

**Comment by pbiswas101** [comment]
Don't add a logo as we haven't decided on it yet!

**Comment by Suparnapaul393** [comment]
thank you

**Comment by Nimmo1993** [comment]
subarna please take the updated version of the repo and commit your changes there's substantial amount of merge conflict

**Comment by Suparnapaul393** [comment]
how to update that can you tell me

**Comment by Nimmo1993** [comment]
fork the project again/pull origin and make your changes. keep a copy of your work in another place and then copy the changed parts from there to the forked one.

**Comment by Suparnapaul393** [comment]
Thank you soooo much...

**Pull request closed without merging**
