### PR TITLE
Created forgot password page

### PR DESCRIPTION
**Pull request by aartigurjar**
I have created 'Forgot Password' page and linked it with the login page.
Here is the live link: https://aartigurjar.github.io/task-master/forgotpassword.html

### CODE REVIEW

**Comment by Rajrox97** [comment]
Squash commits. I am reviewing the page. Let's see what other mods have to say.

**Comment by RatnadeepBiswakarma** [comment]
Hi @aartigurjar do we need the password field here? Only email input field is enough and after all user will come on this  page to reset their forgotten password. aren't it?

**Comment by sahkal** [comment]
I think we need to work on this matter , 1st of all yes ratnadeep is right we dont need password section in this forget password page , the next thing after the email is filled , clicking on reset should send a confirmation email to the account holder , with link of the reset password page where user name or id , will be provided along with new password and confirm password sections . After which changes will done as a permanent solution.

**Comment by aartigurjar** [comment]
@sahkal @RatnadeepBiswakarma Yes, the page could also have only the email input. But I thought that in the  password field, the user would input the new password and click on the 'reset password' button which will send a confirmation email to the user asking if the user wants to keep the new password or not. If the user confirms yes, then the password will reset. However, if you don't want the page to work this way, let me know what changes do I need to make.

**Comment by sahkal** [comment]
Yeah, I get what you are saying... But the question is of security... The level security is reduced in your case.

**Comment by RatnadeepBiswakarma** [comment]
the password field may need if the mods and co-mods wanted to implement some advanced password reset recovery such as Gmail password reset. They asked the user to enter the last password he remembered. I think we don't need such high-end security here. so as @sahkal said first consult with mods and co-mods.

**Comment by Rajrox97** [comment]
Only email input will do @aartigurjar

**Pull request closed without merging**
