### PR TITLE
I have added the user profile photo and some other details.

### PR DESCRIPTION
**Pull request by RatnadeepBiswakarma**

### CODE REVIEW

**Comment by pbiswas101** [comment]
Please provide the live link to your changes so that we can see the changes you made! Also try to squash your commits into one.

**Comment by RatnadeepBiswakarma** [comment]
here is the link  https://ratnadeepbiswakarma.github.io/task-master/profile.html

**Comment by pbiswas101** [comment]
Great Ratnadeep, just add a **_button_** below the profile pic for an option to upload the profile pic like so!






 No need to make the button functional yet just add it! And also try to _squash your commits into one_!

**Comment by souro18** [comment]
Not responsive in my phone. Mods please look into this before merging if it is really not responsive or it is happening only in my device. And total 18 files were changed. But pull request says "user profile photo and other changes". That is a lot of changes.

**Comment by Rajrox97** [comment]
i would also like @RatnadeepBiswakarma to give live links of all the pages. So that we can verify easily that no page was altered and then we can merge it once it becomes responsive.  I hope that is reasonable.

**Comment by RatnadeepBiswakarma** [comment]
with a heavy effort I managed to resolved the conflict and now working on its responsiveness. @pbiswas101 @Rajrox97 have a look. And other pages are totally untouched. The main problem occurred due to the commit reset.

**Comment by RatnadeepBiswakarma** [comment]
screenshot 43
I have fixed all issue at profile page. Made some modification at UI part so that look better. And all the live page  https://ratnadeepbiswakarma.github.io/task-master/profile.html

**Comment by Rajrox97** [comment]
@RatnadeepBiswakarma  great job man! Still there is this one issue. 
image

And, there has been some PR accepts in between , don't forget to fetch the changes. ;)

**Comment by shashank-sharma** [comment]
@RatnadeepBiswakarma Let me help you with Squashing

1. Obviously make sure that you made all the changes
2. Do `git log` and determine how many commits you need to squash. For example let us say it is 5
3. Type: `git rebase -i HEAD~5
4. Now this will open one editor with many text like
```
pick Commit 1
pick Commit 2
``` 
... etc
5. Now change first Commit 1 from `pick` to `r` and rest all `pick` to `F`
```
r Commit 1
F commit 2
F commit 3
```
etc ...
6. Now save this file and exit. Next this will open another file automatically with one commit message.
Change that commit message, which will be your squashed commit.
7. Now push your changes back to forked repo by 
`git push -u origin +master`
You can do --force push or make use of +.

I hope this will help you

**Comment by RatnadeepBiswakarma** [comment]
hi @Rajrox97 thanks for your suggestion and I will look into this matter. hi @shashank-sharma I have tried to squash my commit but when I am trying to squash my commit it is showing that the commit contains some changes and files are modified. I am posting some of the screenshot and will contact you DM on slack.

**Comment by RatnadeepBiswakarma** [comment]
screenshot 46
hi @shashank-sharma here is the screenshot of the issue tell me what to do?

**Comment by goss-gowtham** [comment]
Hi @RatnadeepBiswakarma , 
Try merging the Conflicts in the Editor which will have something like (When you locate to the conflict file, in your case css/login.css)
>>>>>>>Head
My changes
=======
Other changes
<<<<<<<Master
So, Keep the change you want to, and use `git add <your-file>`.
Then try `git rebase --continue`. If you encounter the file you already `added`, then you can try `git rebase --skip`. This should increase the (master|REBASE -i 9/16) from 8/16.
So repeat the steps for the conflict files and complete the rebase.
I guess this would help. Correct me if I am wrong.

**Pull request closed without merging**
