### PR TITLE
Homepage Contact Form UI Improved

### PR DESCRIPTION
**Pull request by creatorisback**
I have fixed some form issues please review and merge

contact form

### CODE REVIEW

**Comment by shashank-sharma** [comment]
If possible please add the link to your github pages so that we can view this change live.

**Comment by creatorisback** [comment]
How do i mount my branch to github page it has only option to mount master branch

**Comment by shashank-sharma** [comment]
Your forked repo > Settings > Github Pages > Select source from none to branch > Wait 10 seconds / refresh the page > There you will see one link, just click on it and you will be able to view it.

**Comment by Nimmo1993** [comment]
hi could you please take the updated version of the repo and commit your changes.. there's merge conflict..

**Comment by creatorisback** [comment]
https://creatorisback.github.io/task-master/

**Comment by creatorisback** [comment]
If you review and like that i'll resolve conflicts

**Comment by Nimmo1993** [comment]
looks good
...send me the updated version...

**Pull request merged**
