### PR TITLE
#121 Changed size of submit button on homepage

### PR DESCRIPTION
**Pull request by amarjeetsingh1999**
#121
The size of submit button under the contact section of homepage looked inappropriate. So it is fixed.

### CODE REVIEW

**Comment by Rajrox97** [comment]
Hi @amarjeetsingh1999 . Please submit the live link of your change as well.

**Comment by amarjeetsingh1999** [comment]
@Rajrox97  can you please guide me on how to make these changes live.

**Comment by amarjeetsingh1999** [comment]
image
image
@shashank-sharma  I followed those steps but it is showing an error on opening that link. Could you please help me in resolving this problem.

**Comment by shashank-sharma** [comment]
Hi @amarjeetsingh1999 
The problem is that you changed the styling of mail us section button rather than changing the Contact form button. 
Have a look at the screenshot here at bottom right, there the button is really small:

screenshot from 2018-04-22 17-15-01

At the same time you can't simply fix it by using:
`style="width: 20%"`
Because if you will do that, then in smaller screen it becomes quite small. See this:

screenshot from 2018-04-22 17-18-10

So please come up with effective solution.

**Pull request closed without merging**
