### PR TITLE
[Added] Hover Effect on Social Media Icons.

### PR DESCRIPTION
**Pull request by utkarsh2102**
In reference to #169,
The hover effect on the social media icons have been added.
Preview page : https://utkarsh2102.github.io/task-master/
Let me know if there's anything I can fix?
CC : @pbiswas101

### CODE REVIEW

**Comment by pbiswas101** [comment]
Aditya is going to make a PR fixing the contact linkage with navigation and removal of Mail Us section!
@utkarsh2102 after we merge his PR you have to sync your repo once more & make this PR again!
It would be nice to have the hover effect on not just social media icons but also in the names e.g. **Twitter**, **Facebook**, etc.

**Comment by utkarsh2102** [comment]
Okay, sure.
Waiting for his PR.

**Comment by Rajrox97** [comment]
@utkarsh2102  u can go ahead and make necessary changes.

**Comment by utkarsh2102** [comment]
I'm closing this as a new PR #183 has been opened for the same.

**Pull request closed without merging**
