### PR TITLE
Login page is responsive now

### PR DESCRIPTION
**Pull request by creatorisback**
I have made login page responsive please review changes at below URL
https://creatorisback.github.io/task-master/login.html

### CODE REVIEW

**Comment by creatorisback** [comment]
I've also fixed mobile navigation issues please preview above link to verify

**Comment by creatorisback** [comment]
Fixed navigation bar of login page and included custom.css for login page

changes live at
https://creatorisback.github.io/task-master/login.html

**Comment by creatorisback** [comment]
Navigation links added on login screen so we can go back to each section from login page

**Comment by bhaskarSingh** [comment]
forget password is overlapping with the login button

**Comment by creatorisback** [comment]
Fixed overlapping forgot password text

**Pull request closed without merging**
