### PR TITLE
fixed the footer bug

### PR DESCRIPTION
**Pull request by abulhayat1**
# Issues solved #60 

fixed the footer of login page which was not same as the one in homepage.

### CODE REVIEW

**Comment by shashank-sharma** [comment]
It would be great if you can elaborate what you really fixed, I am not able to understand what bug you fixed, and now how it is looking now ? Screenshot would be great.

**Comment by pbiswas101** [comment]
send a screenshot! @abulhayat1

**Comment by abulhayat1** [comment]
fix

**Comment by shashank-sharma** [comment]
Did you tried to fix #60 bug ?

**Comment by abulhayat1** [comment]
yes @shashank-sharma

**Comment by shashank-sharma** [comment]
@abulhayat1 Then please mention the issue id in your description so that we can know what you really fixed. Also in future please follow these guidelines which are mentioned in this link: 
https://github.com/UdacityFrontEndScholarship/task-master/blob/master/CONTRIBUTING.md

**Pull request merged**
