### PR TITLE
Resolved Issue #121

### PR DESCRIPTION
**Pull request by amarjeetsingh1999**
The size of submit button in contact section of homepage is fixed and is even compatible with small sized browser window.
The live link is: https://amarjeetsingh1999.github.io/task-master/

### CODE REVIEW

**Comment by Rajrox97** [comment]
hi @amarjeetsingh1999  can you please squash your commits ? Also, please change the color of the submit button to Teal. :) 

Thanks .

**Comment by amarjeetsingh1999** [comment]
Hi @Rajrox97 can you please guide me on how to squash all these commits. And now if i change the color of the submit button, can i include that commit also in this PR? If yes then how to do that?
Thank you

**Comment by amarjeetsingh1999** [comment]
image
image

When i am trying to squash my commits by using git rebase command then i am facing a merge conflict error. Though initially on checking git status it shows no conflicts at all but afterward shows merge conflict. So i tried fixing this merge conflict error many times by rejecting incoming changes and at other time by accepting incoming changes. But then it again shows merge conflict when i try squashing.  Please help me in resolving this issue.

**Comment by amarjeetsingh1999** [comment]
Would create a PR with all the changes in one single commit because the error in squashing these commits doesn't seem to get resolved.

**Pull request closed without merging**
