### PR TITLE
Adding a loading screen with gitignore and editorconfig

### PR DESCRIPTION
**Pull request by vattytrivedi**
- I am raising this pull request to add a loading screen so that it just not popup directly when all the content is loaded, or loading. 
- Also adding a gitignore file to avoid adding unnecessary folders and files on GitHub like .idea file.
- Making an editorconfig file which is helpful in keeping the same style of writing code whichever IDE is used for development.

Link: [view](https://vattytrivedi.github.io/task-master/)

### CODE REVIEW

**Comment by pbiswas101** [comment]
send the github.io link to your repo then we'll merge this request! or a screenshot! Since this request has conflicts, that's why I'm asking!

**Comment by DeepPurohit** [comment]
Only add the `loading` thing to main or else make a branch and after testing merge it to master file

**Comment by pbiswas101** [comment]
@vattytrivedi make your repo up to date with the master branch of this one at first, then make the pull request!

**Comment by DeepPurohit** [comment]
@vattytrivedi make changes to your elements only and place comments of what changes you have made along with date and your name.

**Comment by vattytrivedi** [comment]
@pbiswas101 When I had made the PR it had no conflicts. Anyways no issue I will raise a new one.

**Pull request closed without merging**
