### PR TITLE
Update init.css

### PR DESCRIPTION
**Pull request by shadab97**
hi team  i would like to add hover effect to top navigation bar because it is very good user experience and also the user knows where he is pointing 
i also add feature to increase font size because it look attractive when user point to text and it get bigger in nav-wrapper
capture2

### CODE REVIEW

**Comment by pbiswas101** [comment]
send a live link @shadab97

**Comment by Rajrox97** [comment]
@shadab97 hi shadab. This is not what i think we would prefer. First off, the highlight is taking place outside the navigation bar. Secondly, please use color from the Primary color palette (grey->white) from our readme to highlight the buttons.

**Comment by shadab97** [comment]
@Rajrox97  thankyou 
 ok have a look team 
i updated the code and use primary color 
https://shadab97.github.io/task-master/

**Comment by shashank-sharma** [comment]
@shadab97 Your PR looks reasonable as it enhances the UI of our page. I suggest you squash all the commits and then we will accept your PR if 2 moderators agree with your PR.
In my case I haven no problem.

**Pull request closed without merging**
